// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: rewriter/proto/rewriter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RewriterClient is the client API for Rewriter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RewriterClient interface {
	Rewrite(ctx context.Context, in *RewriteRequest, opts ...grpc.CallOption) (*RewriteReply, error)
}

type rewriterClient struct {
	cc grpc.ClientConnInterface
}

func NewRewriterClient(cc grpc.ClientConnInterface) RewriterClient {
	return &rewriterClient{cc}
}

func (c *rewriterClient) Rewrite(ctx context.Context, in *RewriteRequest, opts ...grpc.CallOption) (*RewriteReply, error) {
	out := new(RewriteReply)
	err := c.cc.Invoke(ctx, "/proto.Rewriter/Rewrite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RewriterServer is the server API for Rewriter service.
// All implementations must embed UnimplementedRewriterServer
// for forward compatibility
type RewriterServer interface {
	Rewrite(context.Context, *RewriteRequest) (*RewriteReply, error)
	mustEmbedUnimplementedRewriterServer()
}

// UnimplementedRewriterServer must be embedded to have forward compatible implementations.
type UnimplementedRewriterServer struct {
}

func (UnimplementedRewriterServer) Rewrite(context.Context, *RewriteRequest) (*RewriteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rewrite not implemented")
}
func (UnimplementedRewriterServer) mustEmbedUnimplementedRewriterServer() {}

// UnsafeRewriterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RewriterServer will
// result in compilation errors.
type UnsafeRewriterServer interface {
	mustEmbedUnimplementedRewriterServer()
}

func RegisterRewriterServer(s grpc.ServiceRegistrar, srv RewriterServer) {
	s.RegisterService(&Rewriter_ServiceDesc, srv)
}

func _Rewriter_Rewrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RewriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RewriterServer).Rewrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Rewriter/Rewrite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RewriterServer).Rewrite(ctx, req.(*RewriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rewriter_ServiceDesc is the grpc.ServiceDesc for Rewriter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rewriter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Rewriter",
	HandlerType: (*RewriterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Rewrite",
			Handler:    _Rewriter_Rewrite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rewriter/proto/rewriter.proto",
}
