// protoc --go_out=. --go_opt=paths=source_relative \
//	--go-grpc_out=. --go-grpc_opt=paths=source_relative \
//	rewriter.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: rewriter/proto/rewriter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RewriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data     []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metadata []byte `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *RewriteRequest) Reset() {
	*x = RewriteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rewriter_proto_rewriter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RewriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteRequest) ProtoMessage() {}

func (x *RewriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rewriter_proto_rewriter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteRequest.ProtoReflect.Descriptor instead.
func (*RewriteRequest) Descriptor() ([]byte, []int) {
	return file_rewriter_proto_rewriter_proto_rawDescGZIP(), []int{0}
}

func (x *RewriteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RewriteRequest) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RewriteReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok   bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RewriteReply) Reset() {
	*x = RewriteReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rewriter_proto_rewriter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RewriteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewriteReply) ProtoMessage() {}

func (x *RewriteReply) ProtoReflect() protoreflect.Message {
	mi := &file_rewriter_proto_rewriter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewriteReply.ProtoReflect.Descriptor instead.
func (*RewriteReply) Descriptor() ([]byte, []int) {
	return file_rewriter_proto_rewriter_proto_rawDescGZIP(), []int{1}
}

func (x *RewriteReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RewriteReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_rewriter_proto_rewriter_proto protoreflect.FileDescriptor

var file_rewriter_proto_rewriter_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x72, 0x65, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x72, 0x65, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x0e, 0x52, 0x65, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x32, 0x0a, 0x0c, 0x52, 0x65, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x41, 0x0a, 0x08,
	0x52, 0x65, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x07, 0x52, 0x65, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x77, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42,
	0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f,
	0x2d, 0x67, 0x6f, 0x73, 0x74, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x72, 0x65, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rewriter_proto_rewriter_proto_rawDescOnce sync.Once
	file_rewriter_proto_rewriter_proto_rawDescData = file_rewriter_proto_rewriter_proto_rawDesc
)

func file_rewriter_proto_rewriter_proto_rawDescGZIP() []byte {
	file_rewriter_proto_rewriter_proto_rawDescOnce.Do(func() {
		file_rewriter_proto_rewriter_proto_rawDescData = protoimpl.X.CompressGZIP(file_rewriter_proto_rewriter_proto_rawDescData)
	})
	return file_rewriter_proto_rewriter_proto_rawDescData
}

var file_rewriter_proto_rewriter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rewriter_proto_rewriter_proto_goTypes = []interface{}{
	(*RewriteRequest)(nil), // 0: proto.RewriteRequest
	(*RewriteReply)(nil),   // 1: proto.RewriteReply
}
var file_rewriter_proto_rewriter_proto_depIdxs = []int32{
	0, // 0: proto.Rewriter.Rewrite:input_type -> proto.RewriteRequest
	1, // 1: proto.Rewriter.Rewrite:output_type -> proto.RewriteReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rewriter_proto_rewriter_proto_init() }
func file_rewriter_proto_rewriter_proto_init() {
	if File_rewriter_proto_rewriter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rewriter_proto_rewriter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RewriteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rewriter_proto_rewriter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RewriteReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rewriter_proto_rewriter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rewriter_proto_rewriter_proto_goTypes,
		DependencyIndexes: file_rewriter_proto_rewriter_proto_depIdxs,
		MessageInfos:      file_rewriter_proto_rewriter_proto_msgTypes,
	}.Build()
	File_rewriter_proto_rewriter_proto = out.File
	file_rewriter_proto_rewriter_proto_rawDesc = nil
	file_rewriter_proto_rewriter_proto_goTypes = nil
	file_rewriter_proto_rewriter_proto_depIdxs = nil
}
