// protoc --go_out=. --go_opt=paths=source_relative \
//	--go-grpc_out=. --go-grpc_opt=paths=source_relative \
//	bypass.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: bypass.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BypassRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *BypassRequest) Reset() {
	*x = BypassRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bypass_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BypassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BypassRequest) ProtoMessage() {}

func (x *BypassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bypass_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BypassRequest.ProtoReflect.Descriptor instead.
func (*BypassRequest) Descriptor() ([]byte, []int) {
	return file_bypass_proto_rawDescGZIP(), []int{0}
}

func (x *BypassRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type BypassReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *BypassReply) Reset() {
	*x = BypassReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bypass_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BypassReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BypassReply) ProtoMessage() {}

func (x *BypassReply) ProtoReflect() protoreflect.Message {
	mi := &file_bypass_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BypassReply.ProtoReflect.Descriptor instead.
func (*BypassReply) Descriptor() ([]byte, []int) {
	return file_bypass_proto_rawDescGZIP(), []int{1}
}

func (x *BypassReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_bypass_proto protoreflect.FileDescriptor

var file_bypass_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x79, 0x70, 0x61, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x0d, 0x42, 0x79, 0x70, 0x61, 0x73, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22, 0x1d, 0x0a, 0x0b, 0x42, 0x79,
	0x70, 0x61, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x32, 0x3c, 0x0a, 0x06, 0x42, 0x79, 0x70,
	0x61, 0x73, 0x73, 0x12, 0x32, 0x0a, 0x06, 0x42, 0x79, 0x70, 0x61, 0x73, 0x73, 0x12, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x79, 0x70, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x79, 0x70, 0x61,
	0x73, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x6f, 0x73, 0x74, 0x2f, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2f, 0x62, 0x79, 0x70, 0x61, 0x73, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bypass_proto_rawDescOnce sync.Once
	file_bypass_proto_rawDescData = file_bypass_proto_rawDesc
)

func file_bypass_proto_rawDescGZIP() []byte {
	file_bypass_proto_rawDescOnce.Do(func() {
		file_bypass_proto_rawDescData = protoimpl.X.CompressGZIP(file_bypass_proto_rawDescData)
	})
	return file_bypass_proto_rawDescData
}

var file_bypass_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bypass_proto_goTypes = []interface{}{
	(*BypassRequest)(nil), // 0: proto.BypassRequest
	(*BypassReply)(nil),   // 1: proto.BypassReply
}
var file_bypass_proto_depIdxs = []int32{
	0, // 0: proto.Bypass.Bypass:input_type -> proto.BypassRequest
	1, // 1: proto.Bypass.Bypass:output_type -> proto.BypassReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bypass_proto_init() }
func file_bypass_proto_init() {
	if File_bypass_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bypass_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BypassRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bypass_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BypassReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bypass_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bypass_proto_goTypes,
		DependencyIndexes: file_bypass_proto_depIdxs,
		MessageInfos:      file_bypass_proto_msgTypes,
	}.Build()
	File_bypass_proto = out.File
	file_bypass_proto_rawDesc = nil
	file_bypass_proto_goTypes = nil
	file_bypass_proto_depIdxs = nil
}
