// protoc --go_out=. --go_opt=paths=source_relative \
//	--go-grpc_out=. --go-grpc_opt=paths=source_relative \
//	p2p.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: p2p/proto/p2p.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpenTunnel asks the plugin to establish a tunnel to the given peer and
// return a local endpoint for it.
//
// peer is opaque to the client: its semantics are defined by the plugin
// itself (rendezvous capability ID, WG public key, custom credential...).
// The client only passes it through.
type OpenTunnelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peer string `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	// network selects the endpoint's semantics: "tcp" (a byte stream; empty
	// means tcp) or "udp" (a datagram endpoint, one datagram per write).
	// Values are validated by the plugin.
	Network string `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
}

func (x *OpenTunnelRequest) Reset() {
	*x = OpenTunnelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_p2p_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTunnelRequest) ProtoMessage() {}

func (x *OpenTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_p2p_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTunnelRequest.ProtoReflect.Descriptor instead.
func (*OpenTunnelRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_p2p_proto_rawDescGZIP(), []int{0}
}

func (x *OpenTunnelRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *OpenTunnelRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

// id is assigned by the server; the client must return it verbatim when
// closing the tunnel.
type OpenTunnelReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// endpoint is the tunnel handle (not interpreted by GOST): a locally
	// dialable "host:port" of the requested network (no scheme).
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Error    string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"` // human-readable reason when ok == false
}

func (x *OpenTunnelReply) Reset() {
	*x = OpenTunnelReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_p2p_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenTunnelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTunnelReply) ProtoMessage() {}

func (x *OpenTunnelReply) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_p2p_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTunnelReply.ProtoReflect.Descriptor instead.
func (*OpenTunnelReply) Descriptor() ([]byte, []int) {
	return file_p2p_proto_p2p_proto_rawDescGZIP(), []int{1}
}

func (x *OpenTunnelReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *OpenTunnelReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OpenTunnelReply) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *OpenTunnelReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CloseTunnelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CloseTunnelRequest) Reset() {
	*x = CloseTunnelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_p2p_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTunnelRequest) ProtoMessage() {}

func (x *CloseTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_p2p_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTunnelRequest.ProtoReflect.Descriptor instead.
func (*CloseTunnelRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_p2p_proto_rawDescGZIP(), []int{2}
}

func (x *CloseTunnelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CloseTunnelReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *CloseTunnelReply) Reset() {
	*x = CloseTunnelReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_p2p_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseTunnelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTunnelReply) ProtoMessage() {}

func (x *CloseTunnelReply) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_p2p_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTunnelReply.ProtoReflect.Descriptor instead.
func (*CloseTunnelReply) Descriptor() ([]byte, []int) {
	return file_p2p_proto_p2p_proto_rawDescGZIP(), []int{3}
}

func (x *CloseTunnelReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type StatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_p2p_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_p2p_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_p2p_proto_p2p_proto_rawDescGZIP(), []int{4}
}

type StatusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tunnels int32 `protobuf:"varint,1,opt,name=tunnels,proto3" json:"tunnels,omitempty"` // future path/status fields are added here
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_p2p_proto_p2p_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_proto_p2p_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_p2p_proto_p2p_proto_rawDescGZIP(), []int{5}
}

func (x *StatusReply) GetTunnels() int32 {
	if x != nil {
		return x.Tunnels
	}
	return 0
}

var File_p2p_proto_p2p_proto protoreflect.FileDescriptor

var file_p2p_proto_p2p_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x32, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x32, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x11,
	0x4f, 0x70, 0x65, 0x6e, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x65, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22,
	0x63, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x6f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x24, 0x0a, 0x12, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x54, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x10, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x0f,
	0x0a, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x27, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x74, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x73, 0x32, 0xbc, 0x01, 0x0a, 0x03, 0x50, 0x32, 0x50,
	0x12, 0x3e, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x75, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x41, 0x0a, 0x0b, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x12,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x54, 0x75, 0x6e,
	0x6e, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x54, 0x75, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x32, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x6f, 0x73, 0x74, 0x2f, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2f, 0x70, 0x32, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_p2p_proto_p2p_proto_rawDescOnce sync.Once
	file_p2p_proto_p2p_proto_rawDescData = file_p2p_proto_p2p_proto_rawDesc
)

func file_p2p_proto_p2p_proto_rawDescGZIP() []byte {
	file_p2p_proto_p2p_proto_rawDescOnce.Do(func() {
		file_p2p_proto_p2p_proto_rawDescData = protoimpl.X.CompressGZIP(file_p2p_proto_p2p_proto_rawDescData)
	})
	return file_p2p_proto_p2p_proto_rawDescData
}

var file_p2p_proto_p2p_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_p2p_proto_p2p_proto_goTypes = []interface{}{
	(*OpenTunnelRequest)(nil),  // 0: proto.OpenTunnelRequest
	(*OpenTunnelReply)(nil),    // 1: proto.OpenTunnelReply
	(*CloseTunnelRequest)(nil), // 2: proto.CloseTunnelRequest
	(*CloseTunnelReply)(nil),   // 3: proto.CloseTunnelReply
	(*StatusRequest)(nil),      // 4: proto.StatusRequest
	(*StatusReply)(nil),        // 5: proto.StatusReply
}
var file_p2p_proto_p2p_proto_depIdxs = []int32{
	0, // 0: proto.P2P.OpenTunnel:input_type -> proto.OpenTunnelRequest
	2, // 1: proto.P2P.CloseTunnel:input_type -> proto.CloseTunnelRequest
	4, // 2: proto.P2P.Status:input_type -> proto.StatusRequest
	1, // 3: proto.P2P.OpenTunnel:output_type -> proto.OpenTunnelReply
	3, // 4: proto.P2P.CloseTunnel:output_type -> proto.CloseTunnelReply
	5, // 5: proto.P2P.Status:output_type -> proto.StatusReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_p2p_proto_p2p_proto_init() }
func file_p2p_proto_p2p_proto_init() {
	if File_p2p_proto_p2p_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_p2p_proto_p2p_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenTunnelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_p2p_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenTunnelReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_p2p_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseTunnelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_p2p_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseTunnelReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_p2p_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_p2p_proto_p2p_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_p2p_proto_p2p_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_p2p_proto_p2p_proto_goTypes,
		DependencyIndexes: file_p2p_proto_p2p_proto_depIdxs,
		MessageInfos:      file_p2p_proto_p2p_proto_msgTypes,
	}.Build()
	File_p2p_proto_p2p_proto = out.File
	file_p2p_proto_p2p_proto_rawDesc = nil
	file_p2p_proto_p2p_proto_goTypes = nil
	file_p2p_proto_p2p_proto_depIdxs = nil
}
